set ENV=development
set NODE_ENV=%ENV%
set VITE_ENV=%NODE_ENV%
set IS_DEBUG=1
set FRONTEND_SECRET=jwt-s3cr3t
set SECRET_KEY=s3cr3t-k3y
set REACT_APP_TOKEN_SECRET=%SECRET_KEY%
set REFRESH_SECRET_KEY=s3cr3t-k3y
set COOKIE_EXPIRATION=86400

set FRONTEND_PORT=3000

set RESERVATION_PORT=8080
set RESERVATION_API=http://localhost:%RESERVATION_PORT%/%ENV%
set VITE_RESERVATION_API=%RESERVATION_API%

set PG_CLIENT=postgres
set PG_USER=postgres
set PG_PASSWD=postgres
set PG_HOST=localhost
set PG_NAME=hotel_%ENV%
set PG_PORT=8081
set PG_URL=%PG_CLIENT%://%PG_USER%:%PG_PASSWD%@%PG_HOST%:%PG_PORT%/%PG_NAME%
